# Generated by Django 6.0.6 on 2026-06-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_ticket_movie_session_alter_ticket_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
